import streamlit as st

st.set_page_config(page_title="Glossary", layout="wide")

st.title("Glossary of Terms")
st.markdown("Reference for all variables, parameters, and concepts used in this simulator.")

# ===========================================
# STATE VARIABLES
# ===========================================
st.header("State Variables")

st.markdown("""
| Symbol | Name | Units | Description |
|--------|------|-------|-------------|
| $C_A$ | Concentration | mol/L | Molar concentration of reactant A in the reactor |
| $T$ | Temperature | K | Reactor temperature |
| $\\mathbf{x}$ | State vector | - | $\\mathbf{x} = [C_A, T]^T$ |
""")

st.divider()

# ===========================================
# REACTOR PARAMETERS
# ===========================================
st.header("Reactor Parameters")

st.markdown("""
| Symbol | Name | Units | Description |
|--------|------|-------|-------------|
| $q$ | Volumetric flow rate | L/min | Rate of fluid flow through the reactor |
| $V$ | Reactor volume | L | Total volume of the reactor vessel |
| $\\tau = V/q$ | Residence time | min | Average time a molecule spends in the reactor |
| $C_{Ai}$ | Inlet concentration | mol/L | Concentration of reactant in the feed stream |
| $T_i$ | Inlet temperature | K | Temperature of the feed stream |
| $T_c$ | Coolant temperature | K | Temperature of the cooling jacket fluid |
""")

st.divider()

# ===========================================
# THERMODYNAMIC PROPERTIES
# ===========================================
st.header("Thermodynamic Properties")

st.markdown("""
| Symbol | Name | Units | Description |
|--------|------|-------|-------------|
| $\\rho$ | Density | g/L | Mass density of the reactor contents |
| $C_p$ | Heat capacity | J/(g·K) | Specific heat capacity at constant pressure |
| $\\Delta H$ | Reaction enthalpy | J/mol | Heat released (negative) or absorbed (positive) per mole of reaction |
| $UA$ | Heat transfer coefficient | W/K | Overall heat transfer coefficient times area |
""")

st.divider()

# ===========================================
# REACTION KINETICS
# ===========================================
st.header("Reaction Kinetics")

st.markdown("""
| Symbol | Name | Units | Description |
|--------|------|-------|-------------|
| $k$ | Reaction rate constant | 1/min | Rate constant at current temperature |
| $k_0$ | Pre-exponential factor | 1/min | Arrhenius frequency factor |
| $E$ | Activation energy | J/mol | Energy barrier for the reaction |
| $R$ | Gas constant | J/(mol·K) | Universal gas constant = 8.314 |
| $r = kC_A$ | Reaction rate | mol/(L·min) | Rate of reactant consumption |
""")

st.markdown("### Arrhenius Equation")
st.latex(r"k = k_0 \exp\left(-\frac{E}{RT}\right)")
st.caption("The reaction rate constant increases exponentially with temperature.")

st.divider()

# ===========================================
# ENERGY BALANCE TERMS
# ===========================================
st.header("Energy Balance Terms")

st.markdown("""
| Term | Formula | Units | Description |
|------|---------|-------|-------------|
| Flow heat | $(q/V)(T_i - T)$ | K/min | Heat added/removed by material flow |
| Reaction heat | $\\frac{(-\\Delta H)}{\\rho C_p} kC_A$ | K/min | Heat generated by exothermic reaction |
| Cooling heat | $\\frac{UA}{V\\rho C_p}(T_c - T)$ | K/min | Heat removed by cooling jacket |
| Net heat | Sum of above | K/min | Total rate of temperature change = $dT/dt$ |
""")

st.divider()

# ===========================================
# EKF VARIABLES
# ===========================================
st.header("Extended Kalman Filter Variables")

st.markdown("""
| Symbol | Name | Dimensions | Description |
|--------|------|------------|-------------|
| $\\hat{\\mathbf{x}}$ | State estimate | 2×1 | Best estimate of $[C_A, T]^T$ |
| $\\mathbf{P}$ | Covariance matrix | 2×2 | Uncertainty in state estimate |
| $\\mathbf{F}$ | State transition matrix | 2×2 | Linearized dynamics (discrete) |
| $\\mathbf{A}$ | Jacobian matrix | 2×2 | Linearized dynamics (continuous) |
| $\\mathbf{H}$ | Measurement matrix | varies | Maps states to measurements |
| $\\mathbf{K}$ | Kalman gain | 2×m | Correction weighting factor |
| $\\mathbf{Q}$ | Process noise covariance | 2×2 | Model uncertainty |
| $\\mathbf{R}$ | Measurement noise covariance | m×m | Sensor uncertainty |
| $\\mathbf{S}$ | Innovation covariance | m×m | Predicted measurement uncertainty |
| $\\mathbf{r}$ | Innovation (residual) | m×1 | Measurement minus prediction |
""")

st.divider()

# ===========================================
# COVARIANCE MATRIX ELEMENTS
# ===========================================
st.header("Covariance Matrix Elements")

st.latex(r"\mathbf{P} = \begin{bmatrix} P_{11} & P_{12} \\ P_{21} & P_{22} \end{bmatrix}")

st.markdown("""
| Element | Name | Interpretation |
|---------|------|----------------|
| $P_{11}$ | Variance of $C_A$ | Uncertainty in concentration estimate |
| $P_{22}$ | Variance of $T$ | Uncertainty in temperature estimate |
| $P_{12} = P_{21}$ | Cross-covariance | Correlation between $C_A$ and $T$ estimates |
""")

st.markdown("""
**Interpreting $P_{12}$:**
- $P_{12} < 0$: Negative correlation (if $T$ increases, $C_A$ likely decreases)
- $P_{12} > 0$: Positive correlation (states move together)
- $P_{12} = 0$: States are uncorrelated
""")

st.divider()

# ===========================================
# TUNING PARAMETERS
# ===========================================
st.header("Tuning Parameters")

st.markdown("""
| Parameter | Effect of Increasing | Typical Range |
|-----------|---------------------|---------------|
| $Q_{C_A}$ | More responsive to Ca changes, noisier | $10^{-8}$ to $10^{-1}$ |
| $Q_T$ | More responsive to T changes, noisier | $10^{-4}$ to $10^{2}$ |
| $R_{C_A}$ | Less trust in Ca sensor, smoother | $10^{-6}$ to $10^{0}$ |
| $R_T$ | Less trust in T sensor, smoother | $10^{-2}$ to $10^{2}$ |
""")

st.markdown("### The Q/R Ratio")
st.markdown("""
The ratio $Q/R$ determines the filter's behavior:
- **High Q/R**: Fast response, noisy estimates (trusts sensor)
- **Low Q/R**: Slow response, smooth estimates (trusts model)
""")

st.divider()

# ===========================================
# ACRONYMS
# ===========================================
st.header("Acronyms")

st.markdown("""
| Acronym | Full Name |
|---------|-----------|
| CSTR | Continuous Stirred Tank Reactor |
| EKF | Extended Kalman Filter |
| ODE | Ordinary Differential Equation |
| RMSE | Root Mean Square Error |
| PDE | Partial Differential Equation |
""")

